/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.senati.proyecto02.gui01;

import com.senati.proyecto02.miClase.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Efrain
 */
public class FrmConsulta01 extends javax.swing.JFrame {

	Conexion obj=new Conexion();
	
	public FrmConsulta01() {
		initComponents();
		cargarDatos();primero();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                txtPrecio = new javax.swing.JTextField();
                txtProducto = new javax.swing.JTextField();
                txtId = new javax.swing.JTextField();
                jPanel1 = new javax.swing.JPanel();
                cmdUltimo = new javax.swing.JButton();
                cmdPrimera = new javax.swing.JButton();
                cmdSiguiente1 = new javax.swing.JButton();
                cmdAnterior1 = new javax.swing.JButton();
                cmdCerrar = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setBackground(new java.awt.Color(51, 0, 204));
                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(51, 51, 255));
                jLabel1.setText("LISTA DE LOS PRODUCTOS");

                jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel2.setText("Producto");

                jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel3.setText("ID");

                jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel4.setText("Precio");

                txtPrecio.setText("txtPrecio");

                txtProducto.setText("txtProducto");

                txtId.setText("txtId");

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movimientos del cursor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(51, 0, 255))); // NOI18N

                cmdUltimo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                cmdUltimo.setText(">|");
                cmdUltimo.setToolTipText("ULTIMO REGISTRO");
                cmdUltimo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cmdUltimoActionPerformed(evt);
                        }
                });

                cmdPrimera.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                cmdPrimera.setText("|<");
                cmdPrimera.setToolTipText("PRIMER REGISTRO");
                cmdPrimera.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cmdPrimeraActionPerformed(evt);
                        }
                });

                cmdSiguiente1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                cmdSiguiente1.setText("<");
                cmdSiguiente1.setToolTipText("SIGUIENTE REGISTRO");
                cmdSiguiente1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cmdSiguiente1ActionPerformed(evt);
                        }
                });

                cmdAnterior1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                cmdAnterior1.setText(">");
                cmdAnterior1.setToolTipText("REGISTRO ANTERIOR");
                cmdAnterior1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cmdAnterior1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cmdPrimera, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdSiguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(cmdAnterior1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmdSiguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmdAnterior1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmdUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmdPrimera, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(33, Short.MAX_VALUE))
                );

                cmdCerrar.setText("CERAR");
                cmdCerrar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cmdCerrarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(147, 147, 147)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel4)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(199, 199, 199)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 185, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(cmdCerrar)
                                .addGap(68, 68, 68))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(162, 162, 162)
                                        .addComponent(jLabel3)
                                        .addContainerGap(656, Short.MAX_VALUE)))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1)
                                .addGap(41, 41, 41)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(27, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cmdCerrar)
                                                .addGap(78, 78, 78))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel3)
                                        .addContainerGap(271, Short.MAX_VALUE)))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void cmdPrimeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrimeraActionPerformed
                // TODO add your handling code here:
		primero();
        }//GEN-LAST:event_cmdPrimeraActionPerformed

        private void cmdSiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSiguiente1ActionPerformed
                // TODO add your handling code here:
		siguientes();
        }//GEN-LAST:event_cmdSiguiente1ActionPerformed

        private void cmdCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCerrarActionPerformed
                // TODO add your handling code here:
		
	try{
		
	obj.rs.close();
	obj.conectar.close();
	System.exit(0);
	
	
	}catch(SQLException e){
		JOptionPane.showMessageDialog(this,e.toString(),"mostrar",1);
	}

        }//GEN-LAST:event_cmdCerrarActionPerformed

        private void cmdAnterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAnterior1ActionPerformed
                // TODO add your handling code here:
		anterior();
        }//GEN-LAST:event_cmdAnterior1ActionPerformed

        private void cmdUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUltimoActionPerformed
                // TODO add your handling code here:
		ultimo();
        }//GEN-LAST:event_cmdUltimoActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FrmConsulta01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FrmConsulta01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FrmConsulta01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FrmConsulta01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FrmConsulta01().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton cmdAnterior1;
        private javax.swing.JButton cmdCerrar;
        private javax.swing.JButton cmdPrimera;
        private javax.swing.JButton cmdSiguiente1;
        private javax.swing.JButton cmdUltimo;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JTextField txtId;
        private javax.swing.JTextField txtPrecio;
        private javax.swing.JTextField txtProducto;
        // End of variables declaration//GEN-END:variables
void cargarDatos(){
	try{
		
	obj.obtenerConexion();
	obj.st=obj.conectar.createStatement(obj.rs.TYPE_SCROLL_SENSITIVE,obj.rs.CONCUR_READ_ONLY);
	obj.rs=obj.st.executeQuery("select ProductID,ProductName, UnitPrice from Products");
	
	
	}catch(SQLException e){
		JOptionPane.showMessageDialog(this,e.toString(),"cargar",1);
	}
}


void mostrarRegistro(){
	try{
		
	txtId.setText(obj.rs.getString(1));
	txtProducto.setText(obj.rs.getString(2));
	txtPrecio.setText(obj.rs.getString(3));
	
	
	}catch(SQLException e){
		JOptionPane.showMessageDialog(this,e.toString(),"mostrar",1);
	}
	
}
void primero(){
	try{
		
	if(obj.rs.first())
		mostrarRegistro();
	
	
	}catch(SQLException e){
		JOptionPane.showMessageDialog(this,e.toString(),"mostrar",1);
	}
	
}
void siguientes(){
	try{
		
	if(obj.rs.next())
		mostrarRegistro();
	
	
	}catch(SQLException e){
		JOptionPane.showMessageDialog(this,e.toString(),"mostrar",1);
	}
}

void anterior(){
	try{
		
	if(obj.rs.previous())
		mostrarRegistro();
	
	
	}catch(SQLException e){
		JOptionPane.showMessageDialog(this,e.toString(),"mostrar",1);
	}
}
void ultimo(){
	
	try{
		
	if(obj.rs.last())
		mostrarRegistro();
	
	
	}catch(SQLException e){
		JOptionPane.showMessageDialog(this,e.toString(),"mostrar",1);
	}
}

	

}

