/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.senati.proyecto02.gui01;

import com.senati.proyecto02.miClase.Conexion;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Efrain
 */
public class FrmMantenimiento_001_1 extends javax.swing.JFrame {

	Conexion obj=new Conexion();
	
	
	
	public FrmMantenimiento_001_1() {
		initComponents();
		listarEmpresa();
		txtID.setEnabled(false);
                Deshabilitar();
                cmbBuscar.setEnabled(true);
                
                
		//txtEmpresa.requestFocus();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        cmbActualizar = new javax.swing.JButton();
        cmbGuardar = new javax.swing.JButton();
        cmbBuscar = new javax.swing.JButton();
        cmbEliminar = new javax.swing.JButton();
        cmbLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Adobe Arabic", 1, 36)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Registro de la Empresa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mantenimientos con DB", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Codigo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Telefono");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Empresa");

        txtEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpresaActionPerformed(evt);
            }
        });
        txtEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmpresaKeyPressed(evt);
            }
        });

        txtID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIDFocusGained(evt);
            }
        });

        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelKeyTyped(evt);
            }
        });

        cmbActualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbActualizar.setText("Actualizar");
        cmbActualizar.setToolTipText("ActualizarRegistro");
        cmbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbActualizarActionPerformed(evt);
            }
        });

        cmbGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbGuardar.setText("Guardar");
        cmbGuardar.setToolTipText("Guardar Registro");
        cmbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGuardarActionPerformed(evt);
            }
        });
        cmbGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbGuardarKeyPressed(evt);
            }
        });

        cmbBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbBuscar.setText("Buscar");
        cmbBuscar.setToolTipText("Buscar Registro");
        cmbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBuscarActionPerformed(evt);
            }
        });

        cmbEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbEliminar.setText("Eliminar");
        cmbEliminar.setToolTipText("Eliminar Registro");
        cmbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEliminarActionPerformed(evt);
            }
        });

        cmbLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbLimpiar.setText("Limpiar");
        cmbLimpiar.setToolTipText("Eliminar Registro");
        cmbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmbGuardar)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cmbBuscar)
                        .addGap(19, 19, 19)
                        .addComponent(cmbActualizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cmbEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbLimpiar)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
        );

        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbLista.setName("tbLista"); // NOI18N
        tbLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void cmbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGuardarActionPerformed
                // TODO add your handling code here:
		guardarRegistro();
		listarEmpresa();
                cmbBuscar.setEnabled(true);
                cmbLimpiar.setEnabled(true);
                cmbGuardar.setEnabled(false);
        }//GEN-LAST:event_cmbGuardarActionPerformed

        private void tbListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaMouseClicked
                // TODO add your handling code here:
		
		 int y;
        try{
            //Guardamos en un entero la fila seleccionada.
            y=tbLista.getSelectedRow();
            if (y == -1){
                JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila.");
            } else {
               

                //String ayuda = tabla.getValueAt(filaseleccionada, num_columna).toString()); 
                txtID.setText((String) tbLista.getValueAt(y, 0));
                txtEmpresa.setText((String) tbLista.getValueAt(y, 1));
		 txtTel.setText((String) tbLista.getValueAt(y, 2));
   
                           }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error: "+ex+"\nInténtelo nuevamente", " .::Error En la Operacion::." ,JOptionPane.ERROR_MESSAGE);
        }        
		
        }//GEN-LAST:event_tbListaMouseClicked

        private void cmbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBuscarActionPerformed
                // TODO add your handling code here:
	int xc=Integer.parseInt(JOptionPane.showInputDialog("Escribe el codigo"));
	txtID.setText(""+xc);
		buscarEmpresa(xc);
          cmbActualizar.setEnabled(true);
          cmbEliminar.setEnabled(true);
          cmbBuscar.setEnabled(false);
          
        }//GEN-LAST:event_cmbBuscarActionPerformed

        private void cmbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbActualizarActionPerformed
                // TODO add your handling code here:
		
		int xc=Integer.parseInt(txtID.getText());
		String nom=txtEmpresa.getText();
		String tel=txtTel.getText();
		actualizarRegistro(xc, nom, tel);
		listarEmpresa();
                
                cmbGuardar.setEnabled(false);
                cmbEliminar.setEnabled(false);
                cmbBuscar.setEnabled(true);
                cmbLimpiar.setEnabled(true);
                cmbActualizar.setEnabled(false);
                limpiar();
        }//GEN-LAST:event_cmbActualizarActionPerformed

        private void cmbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEliminarActionPerformed
                // TODO add your handling code here:
		int xc=Integer.parseInt(txtID.getText());
		eliminarRegistro(xc);
		listarEmpresa();
                limpiar();
                
        }//GEN-LAST:event_cmbEliminarActionPerformed

    private void cmbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
        cmbActualizar.setEnabled(false);
        cmbEliminar.setEnabled(false);
        cmbBuscar.setEnabled(true);
    }//GEN-LAST:event_cmbLimpiarActionPerformed

    private void txtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelKeyTyped

    private void txtTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyPressed
        // TODO add your handling code here:
        cmbGuardar.setEnabled(true);
        cmbBuscar.setEnabled(false);
        cmbLimpiar.setEnabled(false);
    }//GEN-LAST:event_txtTelKeyPressed

    private void cmbGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbGuardarKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cmbGuardarKeyPressed

    private void txtEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpresaActionPerformed

    private void txtEmpresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpresaKeyPressed
        // TODO add your handling code here:
        cmbBuscar.setEnabled(false);
        
    }//GEN-LAST:event_txtEmpresaKeyPressed

    private void txtIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDFocusGained

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FrmMantenimiento_001_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FrmMantenimiento_001_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FrmMantenimiento_001_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FrmMantenimiento_001_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FrmMantenimiento_001_1().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbActualizar;
    private javax.swing.JButton cmbBuscar;
    private javax.swing.JButton cmbEliminar;
    private javax.swing.JButton cmbGuardar;
    private javax.swing.JButton cmbLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLista;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables


void limpiar(){
	txtID.setText(null);
	txtEmpresa.setText(null);
	txtTel.setText(null);
	txtEmpresa.requestFocus();
}

void habilitar(){
	cmbActualizar.setEnabled(true);
	cmbBuscar.setEnabled(true);
	cmbEliminar.setEnabled(true);
	cmbGuardar.setEnabled(true);
}
void Deshabilitar(){
	cmbActualizar.setEnabled(false);
	cmbBuscar.setEnabled(false);
	cmbEliminar.setEnabled(false);
	cmbGuardar.setEnabled(false);
}

void mensaje(String men){
	JOptionPane.showMessageDialog(this, men);
}



void listarEmpresa(){
	DefaultTableModel modelo=new DefaultTableModel();
	modelo.addColumn("Codigo Emp");
	modelo.addColumn("Nombre Emp");
	modelo.addColumn("Telfono Emp");
	try{
	obj.obtenerConexion();
	obj.pst=obj.conectar.prepareStatement("select * from Shippers");
	obj.rs=obj.pst.executeQuery();
	while(obj.rs.next()){
		
		Object datos[]=new Object[3];
		for(int i=0;i<3;i++){
			datos[i]=obj.rs.getString(i+1);
			
		}
		modelo.addRow(datos);
		
	}
	tbLista.setModel(modelo);
	obj.rs.close();
	obj.conectar.close();
		
		
		
	}catch(SQLException e){
		e.getMessage().toString();
	}
	
}



void guardarRegistro(){
	int x=JOptionPane.showConfirmDialog(null, "Desea Guardar Registro?","Guardar",0);
	
	
	if(x==0){
		try{	
			obj.obtenerConexion();
			
			String nombre=txtEmpresa.getText();
			String telefono=txtTel.getText();
		String xguardar="insert into Shippers(CompanyName,Phone) values";
		xguardar+="('"+nombre+"','"+telefono+"')";
		

		
		obj.st=obj.conectar.createStatement();
		obj.st.executeUpdate(xguardar);
		//obj.conectar.close();
		limpiar();
		
			
		}catch(SQLException ee){
		 System.out.print(ee.toString());
		
		}
	
	
	
	}else{
		mensaje("no guardó registros");
		limpiar();
	}

}



void buscarEmpresa(int cod){
    
    try{
       obj.obtenerConexion();
     obj.pst=obj.conectar.prepareStatement("select * from Shippers where ShipperID=?");
      obj.pst.setInt(1, cod);
      obj.rs=obj.pst.executeQuery();
      if(obj.rs.next()){
          txtEmpresa.setText(obj.rs.getString("CompanyName"));
          txtTel.setText(obj.rs.getString("Phone"));
      }else{
          
          mensaje("El codigo no exite");
	  limpiar();
      }
      obj.rs.close();
      obj.conectar.close();
        
    }catch(SQLException e){
        e.getMessage().toString();
    }
    
    
}

  void actualizarRegistro(int xcod,String nom,String tel){
	  try{
	obj.obtenerConexion();
obj.pst=obj.conectar.prepareStatement("update Shippers set CompanyName=?,Phone=? where ShipperID=?");
obj.pst.setString(1, nom);
obj.pst.setString(2, tel);
obj.pst.setInt(3, xcod);
obj.pst.executeUpdate();
mensaje("Datos actualizados");
obj.conectar.close();
 
	  }catch(SQLException e){
	  System.out.print(e.toString());
	  }
	  
	  
	  
	  
  }





void eliminarRegistro(int xcod){
	
	try{
		obj.obtenerConexion();
		
obj.pst=obj.conectar.prepareStatement("delete from Shippers where ShipperID=?");
obj.pst.setInt(1, xcod);
obj.pst.executeUpdate();
mensaje("Datos eliminados");
obj.conectar.close();

	}catch(SQLException x){
		System.out.print(x.toString());
	}
	
	
}


}
